// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }



  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0-an2QLnSrzXBaT8aecKUgriQw76p_mE',
    appId: '1:193958353969:web:500eb8960d3df2e6bec910',
    messagingSenderId: '193958353969',
    projectId: 'spendsense-05c7d060',
    authDomain: 'spendsense-05c7d060.firebaseapp.com',
    storageBucket: 'spendsense-05c7d060.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXvUbjp2pDnDo5UmL9MWfjxlSgewUQDLQ',
    appId: '1:193958353969:android:5209f6e4ba37dc78bec910',
    messagingSenderId: '193958353969',
    projectId: 'spendsense-05c7d060',
    storageBucket: 'spendsense-05c7d060.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA0-an2QLnSrzXBaT8aecKUgriQw76p_mE',
    appId: '1:193958353969:web:e61ff3beca71ddbdbec910',
    messagingSenderId: '193958353969',
    projectId: 'spendsense-05c7d060',
    authDomain: 'spendsense-05c7d060.firebaseapp.com',
    storageBucket: 'spendsense-05c7d060.firebasestorage.app',
  );

}