name: spendsense
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  telephony: 0.2.0
  google_sign_in: ^6.1.5
  flutter_secure_storage: ^9.0.0
  intl: ^0.18.1
  path_provider: ^2.1.2
  path: ^1.8.3
  http: ^1.2.1
  firebase_core: ^3.0.0
  firebase_auth: ^5.0.0
  cupertino_icons: ^1.0.8
  iconly: ^1.0.1
  bloc: ^9.0.0
  flutter_bloc: ^9.1.1
  get: ^4.7.2
  fl_chart: ^1.0.0
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/google_logo.png

  fonts:
    - family: Manrope
      fonts:
        - asset: assets/fonts/Manrope-Regular.ttf
        - asset: assets/fonts/Manrope-Bold.ttf
